### ISSUE TITLE
客户端0.1.12 报错Invalid argument

### ISSUE THREAD

**Issue by molezz** [spongebob888/shadowquic#38]
同样的配置文件，服务器升级0.1.12后无问题
客户端可以正常运行，一旦连接就报错退出
windows 和 linux 客户端都测试过（x64）

客户端log

```
25-06-19 14:05:30.456  INFO shadowquic 0.1.12 running
25-06-19 14:05:33.704 TRACE socks{src="x.x.x.x:64488"}: socks request accepted: www.gstatic.com:443

thread 'main' panicked at shadowquic/src/shadowquic/outbound.rs:190:78:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

client  yaml
```
inbound:
    type: socks
    bind-addr: "127.0.0.1:1080"
outbound:
    type: shadowquic
    addr: "ipv6:1234"
    jls-pwd: "pwd"
    jls-iv: "add12ad"
    server-name: "gg.com" # must be the same as jls_upstream in server
    alpn: ["h3"]
    initial-mtu: 1400
    congestion-control: bbr
    zero-rtt: true
    over-stream: false
log-level: "trace"

```
